// Centralised SEO constants + helpers. Single source of truth for the canonical
// origin used by metadata, the sitemap, robots, the web manifest and JSON-LD.
//
// `SITE_URL` is the apex domain. Both saintsalo.com and www.saintsalo.com serve
// the site, so canonical tags below point everything at the apex to consolidate
// ranking signals (pair this with a www -> apex redirect at the host/DNS level).

export const SITE_URL = "https://saintsalo.com"
export const SITE_NAME = "dl Salo"
export const SITE_DESCRIPTION = "Collection of works and music by LA composer dl Salo"

// External profiles, used for schema.org `sameAs`.
export const SOCIAL_LINKS = ["https://www.instagram.com/saintsalo/"]

// Default social-share card (generated by app/opengraph-image.tsx). Pages that
// define their own `openGraph` object must re-include this, since Next replaces
// the whole field rather than deep-merging the file-convention image back in.
export const DEFAULT_OG_IMAGE = "/opengraph-image"

// Build an absolute URL from a site-relative path (or pass through an absolute
// one). Used where Next's metadataBase resolution doesn't apply (sitemap, JSON-LD).
export const absoluteUrl = (path = ""): string => {
  if (/^https?:\/\//.test(path)) return path
  return `${SITE_URL}${path.startsWith("/") ? "" : "/"}${path}`
}
